apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "justniffer-stack.proxy.name" . }}
  labels:
    {{- include "justniffer-stack.labels" . | nindent 4 }}
    {{- include "justniffer-stack.proxy.selectorLabels" . | nindent 4 }}
spec:
  replicas: {{ .Values.proxy.replicaCount }}
  selector:
    matchLabels:
      {{- include "justniffer-stack.proxy.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "justniffer-stack.labels" . | nindent 8 }}
        {{- include "justniffer-stack.proxy.selectorLabels" . | nindent 8 }}
    spec:
      serviceAccountName: {{ include "justniffer-stack.serviceAccountName" . }}
      containers:
      - name: justniffer-server-proxy-container
        image: {{ include "justserver-image" . }}
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        command:  ["uvicorn", "--log-level", {{ .Values.proxy.logLevel | quote }}, "justserver.proxy:app", "--host", "0.0.0.0", "--port", "8000"]
        env:
        - name: JUSTSERVER_POD_NAMESPACE
          valueFrom: { fieldRef: { fieldPath: metadata.namespace } }
        ports:
        - name: http 
          containerPort: 8000
          protocol: TCP
        resources:
          {{- toYaml .Values.proxy.resources | nindent 14 }}
      {{- include "justniffer-stack.standardProbe" (dict "probeType" "startupProbe" "Values" .Values ) | nindent 8 }}
      {{- include "justniffer-stack.standardProbe" (dict "probeType" "readinessProbe" "Values" .Values ) | nindent 8 }}
      {{- include "justniffer-stack.standardProbe" (dict "probeType" "livenessProbe" "Values" .Values ) | nindent 8 }}

      restartPolicy: Always