apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "justniffer-stack.roleBindingName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "justniffer-stack.labels" . | nindent 4 }}
subjects:
- kind: ServiceAccount
  name: {{ include "justniffer-stack.proxy.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
roleRef:
  kind: Role
  name: {{ include "justniffer-stack.roleName" . }}
  apiGroup: rbac.authorization.k8s.io
