apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "justniffer-stack.roleName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "justniffer-stack.labels" . | nindent 4 }}
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "list", "watch"]
