
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "justniffer-stack.apiSecretName" . }}
  labels:
    {{- include "justniffer-stack.labels" . | nindent 4 }}
    app.kubernetes.io/component: daemon
    app.kubernetes.io/name: {{ include "justniffer-stack.daemon.name" . }}
type: Opaque
data:
  api-key: {{- if .Values.apiKey }}
    {{ .Values.apiKey | b64enc }}
  {{- else }}
    {{ randAlphaNum 32 | b64enc }}
  {{- end }}  
